hse-project/hse-python

- meson.build
- setup.py
Have the checks completed?
- [*] Compile with latest HSE master
- [*] All new and existing unit and functional tests pass
- [*] Code format check passes
- [*] All Commits are signed off
> SSVG-3706 Bump up version to 2.0.2

- .github/workflows/validate_build.yaml
- meson.build
- meson_options.txt
> Disable hse tests

- meson.build
Signed-off-by: LEROY JACOB VARGIS <ljacobvargis@micron.com>
Cleanup and remove some unused meson code
NFSE-5084
Have the checks completed?
> NFSE-5084: cleanup meson code

- docstrings.toml
- hse2/hse.in.pyi
- hse2/hse.in.pyx
- hse2/hse.pxd
- hse2/meson.build
- meson.build
- tests/conftest.py
- tests/test_hse.py
- tests/test_kvdb.py
- tests/test_kvs.py
This is an implementation of the introspection PR and follow-up to the
HSE C implementation.
NFSE-5011
> Add APIs for introspecting HSE

- meson.build
> Stop requiring black

- hse2/hse.in.pyx
- hse2/meson.build
- setup.py
> Always log file and line number in HseException.message

- docstrings.py
- hse2/hse.in.pyi
- hse2/hse.in.pyx
- hse2/hse.pxd
- tests/test_kvdb.py
> Add wrapper for hse_kvdb_mclass_is_configured()

- tests/test_kvdb.py
Signed-off-by: Nabeel M Mohamed <nmeeramohide@micron.com>
NFSE-4065
Have the checks completed?
- [] Code format check passes
> Fix throttling.init_policy test to accommodate new values

- docstrings.py
- hse2/hse.in.pyi
- hse2/hse.in.pyx
- hse2/hse.pxd
> Expose hse_err_ctx to Python

- tests/meson.build
This was already done for HSE.
> Add python to wrapper for gdb purposes

- meson.build
> Disable building HSE docs

- hse2/meson.build
> Remove hse-python dependency decl since it didn't work

- .github/workflows/ci.yaml
> Remove reference to hse:python suite

- .github/PULL_REQUEST_TEMPLATE.md
> Match PR template to hse

- meson.build
- subprojects/hse.wrap
> Bump up version to 2.1.0, change wrap file to use v2.1

- meson.build
- setup.py
> bump up version to 2.2.0

- subprojects/hse.wrap
> hse.wrap use r2.1 tag

- CONTRIBUTING.md
- README.md
> Update docs to match hse-java

- .github/workflows/builds.yaml
- hse2/meson.build
- meson.build
> Cleanup meson a bit

- meson.build
> Add license to project() call

- .github/workflows/shellcheck.yaml
> Fix pattern in shellcheck workflow

- meson.build
> Use native cython compiler

- .github/workflows/builds.yaml
- cross/common.ini
- cross/s390x.ini
- meson.build
> Fix the cross build...for real :)

- .github/workflows/black.yaml
- .github/workflows/builds.yaml
- .github/workflows/checkoss.yaml
- .github/workflows/shellcheck.yaml
> Update actions/checkout to v3

- meson.build
> Make run_target()s visible to parent project

- .github/workflows/builds.yaml
- .github/workflows/shellcheck.yaml
> Move to Fedora 36

- .github/workflows/builds.yaml
Saves us from downloading files all over the internet.
> Cache the Meson packagecache

- .github/workflows/black.yaml
- .github/workflows/builds.ignore.yaml
- .github/workflows/builds.yaml
- .github/workflows/checkoss.yaml
- .github/workflows/shellcheck.ignore.yaml
- .github/workflows/shellcheck.yaml
- meson.build
> Use preconfigured docker images

- .github/workflows/builds.yaml
> Fix ci skip logic

- .github/workflows/builds.yaml
> Don't allow builds to continue if determine-tag fails

- .github/workflows/builds.yaml
> Make Meson packagecache dependent on image

- cross/s390x.ini
> Add page-size to the s390x cross file

- .flake8
- .github/workflows/flake8.ignore.yaml
- .github/workflows/flake8.yaml
- docstrings.py
- hse3/hse.in.pyi
- pp.py
- samples/ex3_cursor.py
> Conform to flake8

- .github/workflows/isort.ignore.yaml
- .github/workflows/isort.yaml
- .isort.cfg
- hse3/hse.in.pyx
- hse3/hse.pxd
- samples/ex1_create.py
- samples/ex2_simple_ops.py
- samples/ex3_cursor.py
- samples/ex4_transactions.py
- setup.py
- tests/test_transaction.py
> Conform to isort

- meson.build
> Adjust default option to HSE default

- meson.build
> Remove hse:db_bench option

- samples/ex6_error_handling.py
- samples/ex7_configuration.py
- tests/common.py
- tests/test_hse.py
> Adjust for socket.* param name changes

- tests/test_cursor.py
- tests/test_kvs.py
Signed-off-by: Gaurav Ramdasi <10132364+gsramdasi@users.noreply.github.com>
NFSE-5171
> Remove use of the cparam suffix.length

- hse3/hse.in.pyi
- hse3/hse.in.pyx
- hse3/hse.pxd
- scripts/build/docstrings.py
> Add support for HSE_ERR_CTX_TXN_EXPIRED

- samples/ex7_configuration.py
Signed-off-by: Nabeel M Mohamed <nmeeramohide@micron.com>
> Remove read_only usage

- subprojects/hse.wrap
> Set wrap file to use v3.0 branch

- pyproject.toml
> Change projecthome link

- .github/workflows/builds.ignore.yaml
- .github/workflows/builds.yaml
> Use Fedora 37 image for CI

- subprojects/hse.wrap
> Use tag for r3.0 in hse.wrap

- meson.build
> Silence warnings from HSE

- hse3/meson.build
- meson.build
- meson_options.txt
- tests/meson.build
We were doing a lot of custom stuff to support older versions of Meson. Just dump it to simplify it all.
> Cleanup Meson usage

- hse3/meson.build
- meson.build
- meson_options.txt
- tests/meson.build
This reverts commit 7b53c642528363a754797bf317dc3a211fadea33.
Reverting commit to avoid meson bug:
- https://github.com/mesonbuild/meson/issues/11157
Signed-off-by: Alex Tomlinson <4172734+alexttx@users.noreply.github.com>
> Revert "Cleanup Meson usage (#81)"

- .github/workflows/builds.ignore.yaml
- .github/workflows/builds.yaml
> Use the affirmative for determining when to run Builds workflow

- hse3/meson.build
- meson.build
- meson_options.txt
- tests/meson.build
This reverts commit 4e232bc1321dadc4d7dfa9bee03656e0e100275e.
> Revert "Revert "Cleanup Meson usage (#81)" (#83)"
